import { OrderEntity } from "../order-taking/entity";

export type CustomerEntity = {
    id: number;
    name: string;
    phoneNumber: string;
    email?: string;
    address?: string;
    dob?: string;
    gender?: string;
    totalCost?: string;
}

const tables: TableEntity[] = [
    {
      id: 1,
      name: "Bàn 1",
      capacity: 4,
      type: "NORMAL",
      location: "Tầng 1",
      isActive: true,
    },
    {
      id: 2,
      name: "Bàn 2",
      capacity: 4,
      type: "NORMAL",
      location: "Tầng 2",
      isActive: true,
    },
    {
      id: 3,
      name: "Bàn 3",
      capacity: 4,
      type: "NORMAL",
      location: "Tầng 3",
      isActive: true,
    },
    {
      id: 4,
      name: "Bàn 4",
      capacity: 4,
      type: "NORMAL",
      location: "Tầng 1",
      isActive: true,
    },
    {
      id: 5,
      name: "Bàn 5",
      capacity: 4,
      type: "NORMAL",
      location: "Tầng 2",
      isActive: true,
    },
    {
      id: 6,
      name: "Bàn 6",
      capacity: 4,
      type: "NORMAL",
      location: "Tầng 3",
      isActive: true,
    },
    {
      id: 7,
      name: "Phòng VIP 1",
      capacity: 4,
      type: "NORMAL",
      location: "VIP 1",
      isActive: true,
    },
    {
      id: 8,
      name: "Phòng VIP 2",
      capacity: 4,
      type: "NORMAL",
      location: "VIP 2",
      isActive: true,
    },
    {
      id: 9,
      name: "Bàn 9",
      capacity: 4,
      type: "NORMAL",
      location: "Tầng 1",
      isActive: true,
    },
    {
      id: 10,
      name: "Bàn 10",
      capacity: 4,
      type: "NORMAL",
      location: "Tầng 2",
      isActive: true,
    },
  ];
  
  export const initOrders: OrderEntity[] = [
    {
      id: 1,
      customerId: 1,
      userId: 1,
      orderStatus: "CONFIRMED",
      totalCost: 125000,
      numberOfPeople: 2,
      note: "Không ớt",
      checkInTime: "2024-04-01T12:00:00",
      checkOutTime: "2024-04-01T13:00:00",
      paymentId: 1,
      totalPrice: 12500,
      promotion: 0,
      needToPay: 12500,
      paymentMethod: "CASH",
      orderItems: [
        {
          id: 1,
          orderId: 1,
          menuItemId: 1,
          orderedQuantity: 3,
          reservedQuantity: 0,
          price: 125000,
          status: "PROCESSING",
        },
        {
          id: 2,
          orderId: 1,
          menuItemId: 2,
          orderedQuantity: 2,
          reservedQuantity: 0,
          price: 12000,
          status: "PROCESSING",
        },
        {
          id: 3,
          orderId: 1,
          menuItemId: 3,
          orderedQuantity: 2,
          reservedQuantity: 1,
          price: 1200000,
          status: "PROCESSING",
        },
      ],
      orderTables: [
        {
          id: 1,
          orderId: 1,
          tableId: 1,
        },
      ],
    },
    {
      id: 2,
      customerId: 2,
      userId: 2,
      orderStatus: "CHECKED_IN",
      totalCost: 125000,
      numberOfPeople: 2,
      note: "Không ớt",
      checkInTime: "2024-04-01T12:00:00",
      checkOutTime: "2024-04-01T13:00:00",
      paymentId: 2,
      totalPrice: 12500,
      promotion: 500,
      needToPay: 12000,
      paymentMethod: "CASH",
      orderItems: [
        {
          id: 4,
          orderId: 2,
          menuItemId: 1,
          orderedQuantity: 2,
          reservedQuantity: 0,
          price: 125000,
          status: "PROCESSING",
        },
        {
          id: 5,
          orderId: 2,
          menuItemId: 2,
          orderedQuantity: 2,
          reservedQuantity: 0,
          price: 12000,
          status: "PROCESSING",
        },
        {
          id: 6,
          orderId: 2,
          menuItemId: 3,
          orderedQuantity: 2,
          reservedQuantity: 1,
          price: 1200000,
          status: "PROCESSING",
        },
      ],
      orderTables: [
        {
          id: 2,
          orderId: 2,
          tableId: 3,
        },
      ],
    },
    {
      id: 3,
      customerId: 3,
      userId: 3,
      orderStatus: "ABANDONED",
      totalCost: 125000,
      numberOfPeople: 2,
      note: "Không ớt",
      checkInTime: "2024-04-01T12:00:00",
      checkOutTime: "2024-04-01T13:00:00",
      paymentId: 3,
      totalPrice: 12500,
      promotion: 0,
      needToPay: 12500,
      paymentMethod: "CASH",
      orderItems: [
        {
          id: 7,
          orderId: 3,
          menuItemId: 1,
          orderedQuantity: 2,
          reservedQuantity: 0,
          price: 125000,
          status: "PROCESSING",
        },
        {
          id: 8,
          orderId: 3,
          menuItemId: 2,
          orderedQuantity: 2,
          reservedQuantity: 0,
          price: 12000,
          status: "PROCESSING",
        },
        {
          id: 9,
          orderId: 3,
          menuItemId: 3,
          orderedQuantity: 2,
          reservedQuantity: 1,
          price: 1200000,
          status: "PROCESSING",
        },
      ],
      orderTables: [
        {
          id: 3,
          orderId: 3,
          tableId: 5,
        },
      ],
    },
    {
      id: 4,
      customerId: 4,
      userId: 4,
      orderStatus: "CANCELLED",
      totalCost: 125000,
      numberOfPeople: 2,
      note: "Không ớt",
      checkInTime: "2024-04-01T12:00:00",
      checkOutTime: "2024-04-01T13:00:00",
      paymentId: 4,
      totalPrice: 12500,
      promotion: 0,
      needToPay: 12500,
      paymentMethod: "CASH",
      orderItems: [
        {
          id: 10,
          orderId: 4,
          menuItemId: 1,
          orderedQuantity: 2,
          reservedQuantity: 0,
          price: 125000,
          status: "PROCESSING",
        },
        {
          id: 11,
          orderId: 4,
          menuItemId: 2,
          orderedQuantity: 2,
          reservedQuantity: 0,
          price: 12000,
          status: "PROCESSING",
        },
        {
          id: 12,
          orderId: 4,
          menuItemId: 3,
          orderedQuantity: 2,
          reservedQuantity: 1,
          price: 1200000,
          status: "PROCESSING",
        },
      ],
      orderTables: [
        {
          id: 4,
          orderId: 4,
          tableId: 7,
        },
      ],
    },
    {
      id: 5,
      customerId: 5,
      userId: 5,
      orderStatus: "COMPLETED",
      totalCost: 125000,
      numberOfPeople: 2,
      note: "Không ớt",
      checkInTime: "2024-04-01T12:00:00",
      checkOutTime: "2024-04-01T13:00:00",
      paymentId: 5,
      totalPrice: 12500,
      promotion: 0,
      needToPay: 12500,
      paymentMethod: "CASH",
      orderItems: [
        {
          id: 13,
          orderId: 5,
          menuItemId: 1,
          orderedQuantity: 2,
          reservedQuantity: 0,
          price: 125000,
          status: "PROCESSING",
        },
        {
          id: 14,
          orderId: 5,
          menuItemId: 2,
          orderedQuantity: 2,
          reservedQuantity: 0,
          price: 12000,
          status: "PROCESSING",
        },
        {
          id: 15,
          orderId: 5,
          menuItemId: 3,
          orderedQuantity: 2,
          reservedQuantity: 1,
          price: 1200000,
          status: "PROCESSING",
        },
      ],
      orderTables: [
        {
          id: 5,
          orderId: 5,
          tableId: 9,
        },
      ],
    },
  ];
  
  const customers: CustomerEntity[] = [
    {
      id: 1,
      name: "Nguyễn Văn A",
      phoneNumber: "0123456789",
      email: "nguyenvana@gmail.com",
      address: "Hà Nội",
      dob: "1990-01-01",
      gender: "male",
      totalCost: "1000000",
    },
    {
      id: 6,
      name: "Nguyễn Văn An",
      phoneNumber: "0123456789",
      email: "nguyenvana@gmail.com",
      address: "Hà Nội",
      dob: "1990-01-01",
      gender: "male",
      totalCost: "1000000",
    },
    {
      id: 7,
      name: "Nguyễn Văn Anh",
      phoneNumber: "0123456789",
      email: "nguyenvana@gmail.com",
      address: "Hà Nội",
      dob: "1990-01-01",
      gender: "male",
      totalCost: "1000000",
    },
    {
      id: 2,
      name: "Nguyễn Văn B",
      phoneNumber: "0123456789",
      email: "",
    },
    {
      id: 3,
      name: "Nguyễn Văn C",
      phoneNumber: "0123456789",
      email: "",
    },
    {
      id: 4,
      name: "Nguyễn Văn D",
      phoneNumber: "0123456789",
    },
    {
      id: 5,
      name: "Nguyễn Văn E",
      phoneNumber: "0123456789",
    },
  ];