import { cookies } from "next/headers";
import "./globals.css";

import LoginUserProvider from "@/components/LoginUserProvider";
import { decodeJWT } from "@/utils/JWTDecoder";

export const metadata = {
  title: "Teamio - Ứng dụng quản lý nhà hàng",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const token = cookieStore.get("token");

  let user = null;
  if (token) {
    const payload = decodeJWT(token.value);
    user = { userId: payload.sub, role: payload.scope };
  }

  return (
    <html lang="vi">
      <body>
        <LoginUserProvider user={user}>
          <main className="font-nunito">{children}</main>
        </LoginUserProvider>
      </body>
    </html>
  );
}
